# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=1573810614.719477, verbose_name='更新时间'),
        ),
    ]
